include:
  - board: nice_nano//zmk
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano//zmk
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
  - board: nice_nano//zmk
    shield: settings_reset
